import { imageFor } from '@/lib/helpers'
import type { Product, SharedSpaceProfile } from '@/lib/localdb'

export type SharedSpace = SharedSpaceProfile & {
  id: string
  title: string
  slug: string
  img: string
  description: string
}

export function productToSharedSpace(product: Product): SharedSpace | null {
  if ((product as any)?.vertical !== 'shared_space' || !product.spaceProfile) return null
  const profile = product.spaceProfile
  const host = profile.host || { name: product.seller, avatar: '', bio: '' }
  return {
    ...profile,
    listingKind: profile.listingKind || 'roommate',
    host,
    id: product.id,
    title: product.title,
    slug: product.slug,
    description: (product as any).description || '',
    img: product.img,
  }
}

export const SHARED_SPACES: SharedSpace[] = [
  {
    id: 'space_1',
    title: 'Light-filled room in Surry Hills terrace',
    slug: 'surry-hills-terrace',
    listingKind: 'roommate',
    rentPerWeek: 420,
    bond: 840,
    suburb: 'Surry Hills',
    city: 'Sydney',
    state: 'NSW',
    availableFrom: '2025-12-01',
    stayLength: '6-12 months',
    occupancy: { current: 2, total: 3 },
    type: 'room',
    furnished: true,
    description: 'Creative share house with a sunny courtyard, perfect if you love coffee runs, markets, and having a home office nook.',
    host: {
      name: 'Mia',
      avatar: imageFor('creative host portrait', 200, 200),
      bio: 'Product designer, hybrid work. Loves weekend markets and outdoor cinema nights.',
    },
    amenities: ['Queen bed', 'Built-in robe', 'High-speed fibre', 'Courtyard garden', 'Weekly cleaner'],
    vibe: ['Design crew', 'Pet-friendly', 'Hybrid work setup'],
    img: imageFor('sunny sharehouse bedroom', 960, 640),
  },
  {
    id: 'space_2',
    title: 'Desk in fintech founder loft',
    slug: 'fintech-loft-desk',
    listingKind: 'desk-pass',
    rentPerWeek: 180,
    suburb: 'Collingwood',
    city: 'Melbourne',
    state: 'VIC',
    availableFrom: '2025-11-20',
    stayLength: 'Flexible / month-to-month',
    occupancy: { current: 4, total: 6 },
    type: 'desk',
    furnished: true,
    description: 'Join a loft run by operators building commerce tools. Dedicated sit/stand desk, podcast corner, and guest access to demo days.',
    host: {
      name: 'Arjun',
      avatar: imageFor('startup founder portrait', 200, 200),
      bio: 'Cofounder at LoopPay. Early mornings, investor calls, and dumpling runs.',
    },
    amenities: ['27" monitor', 'Bookable meeting pods', 'Notion wiki access', 'Locker storage'],
    vibe: ['Operator community', 'Hosted demos', 'Late-night builds'],
    img: imageFor('modern loft coworking space', 960, 640),
  },
  {
    id: 'space_3',
    title: 'Master room in beachside duplex',
    slug: 'bondi-beach-master-room',
    listingKind: 'roommate',
    rentPerWeek: 520,
    bond: 1040,
    suburb: 'Bondi Beach',
    city: 'Sydney',
    state: 'NSW',
    availableFrom: '2025-12-15',
    stayLength: '3-9 months',
    occupancy: { current: 1, total: 2 },
    type: 'room',
    furnished: true,
    description: 'Wake up to the ocean. Private ensuite, balcony, and secure board storage. Ideal for remote workers craving morning surfs.',
    host: {
      name: 'Leo',
      avatar: imageFor('surfer portrait beach', 200, 200),
      bio: 'Surf coach + product consultant. Early dawn patrols, mellow evenings.',
    },
    amenities: ['Private ensuite', 'Balcony', 'Secure board rack', 'Underground parking', 'Work-ready nook'],
    vibe: ['Coastal living', 'Wellness friendly', 'Remote work'],
    img: imageFor('modern coastal bedroom with balcony', 960, 640),
  },
  {
    id: 'space_4',
    title: 'Converted warehouse micro studio',
    slug: 'warehouse-micro-studio',
    listingKind: 'roommate',
    rentPerWeek: 390,
    suburb: 'West End',
    city: 'Brisbane',
    state: 'QLD',
    availableFrom: '2025-11-28',
    stayLength: '2-6 months',
    occupancy: { current: 3, total: 4 },
    type: 'studio',
    furnished: true,
    description: 'Private micro studio inside a warehouse collective. Shared maker tools, rooftop cinema, and communal dinners twice a week.',
    host: {
      name: 'Sam & Tash',
      avatar: imageFor('creative couple portrait', 200, 200),
      bio: 'Run a slow-fashion label downstairs. Always prototyping, always hosting.',
    },
    amenities: ['Kitchenette', 'Rooftop cinema', 'Workshop access', 'Laundry included'],
    vibe: ['Maker lab', 'Community dinners', 'Event friendly'],
    img: imageFor('warehouse micro studio interior', 960, 640),
  },
  {
    id: 'space_5',
    title: 'CBD executive crash pad',
    slug: 'cbd-executive-pad',
    listingKind: 'lease-transfer',
    rentPerWeek: 680,
    suburb: 'Barangaroo',
    city: 'Sydney',
    state: 'NSW',
    availableFrom: '2025-11-18',
    stayLength: 'Weekday only / commuter plan',
    occupancy: { current: 1, total: 2 },
    type: 'room',
    furnished: true,
    description: 'Weeknight base for interstate execs. Access to building gym, meeting suite, concierge freight forwarding.',
    host: {
      name: 'Priya',
      avatar: imageFor('professional host portrait', 200, 200),
      bio: 'Corporate development lead. Lives between Sydney & Singapore.',
    },
    amenities: ['Hotel-grade linen', 'Onsite gym & pool', 'Smart lock', 'Freshly stocked pantry'],
    vibe: ['Corporate ready', 'Quiet weeknights', 'Concierge services'],
    img: imageFor('luxury apartment bedroom city view', 960, 640),
  },
  {
    id: 'space_6',
    title: 'Regional retreat cabin desk',
    slug: 'regional-retreat-cabin-desk',
    listingKind: 'desk-pass',
    rentPerWeek: 260,
    suburb: 'Daylesford',
    city: 'Regional VIC',
    state: 'VIC',
    availableFrom: '2025-11-25',
    stayLength: 'Min 4 weeks',
    occupancy: { current: 2, total: 3 },
    type: 'desk',
    furnished: true,
    description: 'Need a seasonal reset? Desk plus guest room rotation for founders cycling through deep-work sprints.',
    host: {
      name: 'Harper',
      avatar: imageFor('host portrait cabin', 200, 200),
      bio: 'Ex-agency lead turned retreat host. Loves cooking sessions + nature hikes.',
    },
    amenities: ['Dual monitor desk', 'Forest trails', 'Infrared sauna', 'Chef kitchen'],
    vibe: ['Deep work', 'Slow living', 'Founder residencies'],
    img: imageFor('cozy cabin workspace', 960, 640),
  },
]
