/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ClerkRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as BlogIndexImport } from './routes/blog/index'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as MarketplaceLayoutImport } from './routes/marketplace/_layout'
import { Route as BlogNewImport } from './routes/blog/new'
import { Route as BlogManageImport } from './routes/blog/manage'
import { Route as errors503Import } from './routes/(errors)/503'
import { Route as errors500Import } from './routes/(errors)/500'
import { Route as errors404Import } from './routes/(errors)/404'
import { Route as errors403Import } from './routes/(errors)/403'
import { Route as errors401Import } from './routes/(errors)/401'
import { Route as authSignUpImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2Import } from './routes/(auth)/sign-in-2'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings/route'
import { Route as MarketplaceLayoutIndexImport } from './routes/marketplace/_layout/index'
import { Route as BlogSlugIndexImport } from './routes/blog/$slug/index'
import { Route as AuthenticatedWarehouseIndexImport } from './routes/_authenticated/warehouse/index'
import { Route as AuthenticatedUsersIndexImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedFleetIndexImport } from './routes/_authenticated/fleet/index'
import { Route as AuthenticatedDriversIndexImport } from './routes/_authenticated/drivers/index'
import { Route as AuthenticatedDeliveryIndexImport } from './routes/_authenticated/delivery/index'
import { Route as AuthenticatedChatsIndexImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexImport } from './routes/_authenticated/apps/index'
import { Route as MarketplaceLayoutMyOrdersImport } from './routes/marketplace/_layout/my-orders'
import { Route as ClerkAuthenticatedUserManagementImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInImport } from './routes/clerk/(auth)/sign-in'
import { Route as BlogSlugEditImport } from './routes/blog/$slug/edit'
import { Route as AuthenticatedSettingsNotificationsImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountImport } from './routes/_authenticated/settings/account'
import { Route as MarketplaceLayoutListingsIndexImport } from './routes/marketplace/_layout/listings/index'
import { Route as MarketplaceLayoutDashboardIndexImport } from './routes/marketplace/_layout/dashboard/index'
import { Route as MarketplaceLayoutCheckoutIndexImport } from './routes/marketplace/_layout/checkout/index'
import { Route as MarketplaceLayoutCartIndexImport } from './routes/marketplace/_layout/cart/index'
import { Route as MarketplaceLayoutOrderTrackImport } from './routes/marketplace/_layout/order/track'
import { Route as MarketplaceLayoutOrderIdImport } from './routes/marketplace/_layout/order/$id'
import { Route as MarketplaceLayoutDashboardLabelsImport } from './routes/marketplace/_layout/dashboard/labels'
import { Route as MarketplaceLayoutDashboardImportImport } from './routes/marketplace/_layout/dashboard/import'
import { Route as MarketplaceLayoutMerchantIdIndexImport } from './routes/marketplace/_layout/merchant/$id/index'
import { Route as MarketplaceLayoutListingSlugIndexImport } from './routes/marketplace/_layout/listing/$slug/index'
import { Route as MarketplaceLayoutDashboardSettingsIndexImport } from './routes/marketplace/_layout/dashboard/settings/index'
import { Route as MarketplaceLayoutDashboardPosIndexImport } from './routes/marketplace/_layout/dashboard/pos/index'
import { Route as MarketplaceLayoutDashboardOrdersIndexImport } from './routes/marketplace/_layout/dashboard/orders/index'
import { Route as MarketplaceLayoutDashboardListingsIndexImport } from './routes/marketplace/_layout/dashboard/listings/index'
import { Route as MarketplaceLayoutDashboardBookingsIndexImport } from './routes/marketplace/_layout/dashboard/bookings/index'
import { Route as MarketplaceLayoutDashboardOrdersAllImport } from './routes/marketplace/_layout/dashboard/orders/all'
import { Route as MarketplaceLayoutDashboardOrderIdImport } from './routes/marketplace/_layout/dashboard/order/$id'

// Create Virtual Routes

const MarketplaceImport = createFileRoute('/marketplace')()

// Create/Update Routes

const MarketplaceRoute = MarketplaceImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRoute,
} as any)

const ClerkRouteRoute = ClerkRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const BlogIndexRoute = BlogIndexImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const MarketplaceLayoutRoute = MarketplaceLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => MarketplaceRoute,
} as any)

const BlogNewRoute = BlogNewImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => rootRoute,
} as any)

const BlogManageRoute = BlogManageImport.update({
  id: '/blog/manage',
  path: '/blog/manage',
  getParentRoute: () => rootRoute,
} as any)

const errors503Route = errors503Import.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRoute,
} as any)

const errors500Route = errors500Import.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const errors404Route = errors404Import.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRoute,
} as any)

const errors403Route = errors403Import.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRoute,
} as any)

const errors401Route = errors401Import.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRoute,
} as any)

const authSignUpRoute = authSignUpImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const authSignIn2Route = authSignIn2Import.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authOtpRoute = authOtpImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const authForgotPasswordRoute = authForgotPasswordImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)

const ClerkauthRouteRoute = ClerkauthRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)

const AuthenticatedSettingsRouteRoute = AuthenticatedSettingsRouteImport.update(
  {
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const MarketplaceLayoutIndexRoute = MarketplaceLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceLayoutRoute,
} as any)

const BlogSlugIndexRoute = BlogSlugIndexImport.update({
  id: '/blog/$slug/',
  path: '/blog/$slug/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedWarehouseIndexRoute =
  AuthenticatedWarehouseIndexImport.update({
    id: '/warehouse/',
    path: '/warehouse/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedSettingsIndexRoute = AuthenticatedSettingsIndexImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any,
)

const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedFleetIndexRoute = AuthenticatedFleetIndexImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedDriversIndexRoute = AuthenticatedDriversIndexImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedDeliveryIndexRoute = AuthenticatedDeliveryIndexImport.update(
  {
    id: '/delivery/',
    path: '/delivery/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const MarketplaceLayoutMyOrdersRoute = MarketplaceLayoutMyOrdersImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => MarketplaceLayoutRoute,
} as any)

const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)

const ClerkauthSignUpRoute = ClerkauthSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)

const ClerkauthSignInRoute = ClerkauthSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)

const BlogSlugEditRoute = BlogSlugEditImport.update({
  id: '/blog/$slug/edit',
  path: '/blog/$slug/edit',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const MarketplaceLayoutListingsIndexRoute =
  MarketplaceLayoutListingsIndexImport.update({
    id: '/listings/',
    path: '/listings/',
    getParentRoute: () => MarketplaceLayoutRoute,
  } as any)

const MarketplaceLayoutDashboardIndexRoute =
  MarketplaceLayoutDashboardIndexImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => MarketplaceLayoutRoute,
  } as any)

const MarketplaceLayoutCheckoutIndexRoute =
  MarketplaceLayoutCheckoutIndexImport.update({
    id: '/checkout/',
    path: '/checkout/',
    getParentRoute: () => MarketplaceLayoutRoute,
  } as any)

const MarketplaceLayoutCartIndexRoute = MarketplaceLayoutCartIndexImport.update(
  {
    id: '/cart/',
    path: '/cart/',
    getParentRoute: () => MarketplaceLayoutRoute,
  } as any,
)

const MarketplaceLayoutOrderTrackRoute =
  MarketplaceLayoutOrderTrackImport.update({
    id: '/order/track',
    path: '/order/track',
    getParentRoute: () => MarketplaceLayoutRoute,
  } as any)

const MarketplaceLayoutOrderIdRoute = MarketplaceLayoutOrderIdImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => MarketplaceLayoutRoute,
} as any)

const MarketplaceLayoutDashboardLabelsRoute =
  MarketplaceLayoutDashboardLabelsImport.update({
    id: '/dashboard/labels',
    path: '/dashboard/labels',
    getParentRoute: () => MarketplaceLayoutRoute,
  } as any)

const MarketplaceLayoutDashboardImportRoute =
  MarketplaceLayoutDashboardImportImport.update({
    id: '/dashboard/import',
    path: '/dashboard/import',
    getParentRoute: () => MarketplaceLayoutRoute,
  } as any)

const MarketplaceLayoutMerchantIdIndexRoute =
  MarketplaceLayoutMerchantIdIndexImport.update({
    id: '/merchant/$id/',
    path: '/merchant/$id/',
    getParentRoute: () => MarketplaceLayoutRoute,
  } as any)

const MarketplaceLayoutListingSlugIndexRoute =
  MarketplaceLayoutListingSlugIndexImport.update({
    id: '/listing/$slug/',
    path: '/listing/$slug/',
    getParentRoute: () => MarketplaceLayoutRoute,
  } as any)

const MarketplaceLayoutDashboardSettingsIndexRoute =
  MarketplaceLayoutDashboardSettingsIndexImport.update({
    id: '/dashboard/settings/',
    path: '/dashboard/settings/',
    getParentRoute: () => MarketplaceLayoutRoute,
  } as any)

const MarketplaceLayoutDashboardPosIndexRoute =
  MarketplaceLayoutDashboardPosIndexImport.update({
    id: '/dashboard/pos/',
    path: '/dashboard/pos/',
    getParentRoute: () => MarketplaceLayoutRoute,
  } as any)

const MarketplaceLayoutDashboardOrdersIndexRoute =
  MarketplaceLayoutDashboardOrdersIndexImport.update({
    id: '/dashboard/orders/',
    path: '/dashboard/orders/',
    getParentRoute: () => MarketplaceLayoutRoute,
  } as any)

const MarketplaceLayoutDashboardListingsIndexRoute =
  MarketplaceLayoutDashboardListingsIndexImport.update({
    id: '/dashboard/listings/',
    path: '/dashboard/listings/',
    getParentRoute: () => MarketplaceLayoutRoute,
  } as any)

const MarketplaceLayoutDashboardBookingsIndexRoute =
  MarketplaceLayoutDashboardBookingsIndexImport.update({
    id: '/dashboard/bookings/',
    path: '/dashboard/bookings/',
    getParentRoute: () => MarketplaceLayoutRoute,
  } as any)

const MarketplaceLayoutDashboardOrdersAllRoute =
  MarketplaceLayoutDashboardOrdersAllImport.update({
    id: '/dashboard/orders/all',
    path: '/dashboard/orders/all',
    getParentRoute: () => MarketplaceLayoutRoute,
  } as any)

const MarketplaceLayoutDashboardOrderIdRoute =
  MarketplaceLayoutDashboardOrderIdImport.update({
    id: '/dashboard/order/$id',
    path: '/dashboard/order/$id',
    getParentRoute: () => MarketplaceLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: '/'
      fullPath: '/clerk/'
      preLoaderRoute: typeof ClerkauthRouteImport
      parentRoute: typeof ClerkRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteImport
      parentRoute: typeof ClerkRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503Import
      parentRoute: typeof rootRoute
    }
    '/blog/manage': {
      id: '/blog/manage'
      path: '/blog/manage'
      fullPath: '/blog/manage'
      preLoaderRoute: typeof BlogManageImport
      parentRoute: typeof rootRoute
    }
    '/blog/new': {
      id: '/blog/new'
      path: '/blog/new'
      fullPath: '/blog/new'
      preLoaderRoute: typeof BlogNewImport
      parentRoute: typeof rootRoute
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceImport
      parentRoute: typeof rootRoute
    }
    '/marketplace/_layout': {
      id: '/marketplace/_layout'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceLayoutImport
      parentRoute: typeof MarketplaceRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/blog/$slug/edit': {
      id: '/blog/$slug/edit'
      path: '/blog/$slug/edit'
      fullPath: '/blog/$slug/edit'
      preLoaderRoute: typeof BlogSlugEditImport
      parentRoute: typeof rootRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInImport
      parentRoute: typeof ClerkauthRouteImport
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpImport
      parentRoute: typeof ClerkauthRouteImport
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementImport
      parentRoute: typeof ClerkAuthenticatedRouteImport
    }
    '/marketplace/_layout/my-orders': {
      id: '/marketplace/_layout/my-orders'
      path: '/my-orders'
      fullPath: '/marketplace/my-orders'
      preLoaderRoute: typeof MarketplaceLayoutMyOrdersImport
      parentRoute: typeof MarketplaceLayoutImport
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/delivery/': {
      id: '/_authenticated/delivery/'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AuthenticatedDeliveryIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/drivers/': {
      id: '/_authenticated/drivers/'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AuthenticatedDriversIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/fleet/': {
      id: '/_authenticated/fleet/'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedFleetIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/warehouse/': {
      id: '/_authenticated/warehouse/'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof AuthenticatedWarehouseIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/blog/$slug/': {
      id: '/blog/$slug/'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugIndexImport
      parentRoute: typeof rootRoute
    }
    '/marketplace/_layout/': {
      id: '/marketplace/_layout/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceLayoutIndexImport
      parentRoute: typeof MarketplaceLayoutImport
    }
    '/marketplace/_layout/dashboard/import': {
      id: '/marketplace/_layout/dashboard/import'
      path: '/dashboard/import'
      fullPath: '/marketplace/dashboard/import'
      preLoaderRoute: typeof MarketplaceLayoutDashboardImportImport
      parentRoute: typeof MarketplaceLayoutImport
    }
    '/marketplace/_layout/dashboard/labels': {
      id: '/marketplace/_layout/dashboard/labels'
      path: '/dashboard/labels'
      fullPath: '/marketplace/dashboard/labels'
      preLoaderRoute: typeof MarketplaceLayoutDashboardLabelsImport
      parentRoute: typeof MarketplaceLayoutImport
    }
    '/marketplace/_layout/order/$id': {
      id: '/marketplace/_layout/order/$id'
      path: '/order/$id'
      fullPath: '/marketplace/order/$id'
      preLoaderRoute: typeof MarketplaceLayoutOrderIdImport
      parentRoute: typeof MarketplaceLayoutImport
    }
    '/marketplace/_layout/order/track': {
      id: '/marketplace/_layout/order/track'
      path: '/order/track'
      fullPath: '/marketplace/order/track'
      preLoaderRoute: typeof MarketplaceLayoutOrderTrackImport
      parentRoute: typeof MarketplaceLayoutImport
    }
    '/marketplace/_layout/cart/': {
      id: '/marketplace/_layout/cart/'
      path: '/cart'
      fullPath: '/marketplace/cart'
      preLoaderRoute: typeof MarketplaceLayoutCartIndexImport
      parentRoute: typeof MarketplaceLayoutImport
    }
    '/marketplace/_layout/checkout/': {
      id: '/marketplace/_layout/checkout/'
      path: '/checkout'
      fullPath: '/marketplace/checkout'
      preLoaderRoute: typeof MarketplaceLayoutCheckoutIndexImport
      parentRoute: typeof MarketplaceLayoutImport
    }
    '/marketplace/_layout/dashboard/': {
      id: '/marketplace/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/marketplace/dashboard'
      preLoaderRoute: typeof MarketplaceLayoutDashboardIndexImport
      parentRoute: typeof MarketplaceLayoutImport
    }
    '/marketplace/_layout/listings/': {
      id: '/marketplace/_layout/listings/'
      path: '/listings'
      fullPath: '/marketplace/listings'
      preLoaderRoute: typeof MarketplaceLayoutListingsIndexImport
      parentRoute: typeof MarketplaceLayoutImport
    }
    '/marketplace/_layout/dashboard/order/$id': {
      id: '/marketplace/_layout/dashboard/order/$id'
      path: '/dashboard/order/$id'
      fullPath: '/marketplace/dashboard/order/$id'
      preLoaderRoute: typeof MarketplaceLayoutDashboardOrderIdImport
      parentRoute: typeof MarketplaceLayoutImport
    }
    '/marketplace/_layout/dashboard/orders/all': {
      id: '/marketplace/_layout/dashboard/orders/all'
      path: '/dashboard/orders/all'
      fullPath: '/marketplace/dashboard/orders/all'
      preLoaderRoute: typeof MarketplaceLayoutDashboardOrdersAllImport
      parentRoute: typeof MarketplaceLayoutImport
    }
    '/marketplace/_layout/dashboard/bookings/': {
      id: '/marketplace/_layout/dashboard/bookings/'
      path: '/dashboard/bookings'
      fullPath: '/marketplace/dashboard/bookings'
      preLoaderRoute: typeof MarketplaceLayoutDashboardBookingsIndexImport
      parentRoute: typeof MarketplaceLayoutImport
    }
    '/marketplace/_layout/dashboard/listings/': {
      id: '/marketplace/_layout/dashboard/listings/'
      path: '/dashboard/listings'
      fullPath: '/marketplace/dashboard/listings'
      preLoaderRoute: typeof MarketplaceLayoutDashboardListingsIndexImport
      parentRoute: typeof MarketplaceLayoutImport
    }
    '/marketplace/_layout/dashboard/orders/': {
      id: '/marketplace/_layout/dashboard/orders/'
      path: '/dashboard/orders'
      fullPath: '/marketplace/dashboard/orders'
      preLoaderRoute: typeof MarketplaceLayoutDashboardOrdersIndexImport
      parentRoute: typeof MarketplaceLayoutImport
    }
    '/marketplace/_layout/dashboard/pos/': {
      id: '/marketplace/_layout/dashboard/pos/'
      path: '/dashboard/pos'
      fullPath: '/marketplace/dashboard/pos'
      preLoaderRoute: typeof MarketplaceLayoutDashboardPosIndexImport
      parentRoute: typeof MarketplaceLayoutImport
    }
    '/marketplace/_layout/dashboard/settings/': {
      id: '/marketplace/_layout/dashboard/settings/'
      path: '/dashboard/settings'
      fullPath: '/marketplace/dashboard/settings'
      preLoaderRoute: typeof MarketplaceLayoutDashboardSettingsIndexImport
      parentRoute: typeof MarketplaceLayoutImport
    }
    '/marketplace/_layout/listing/$slug/': {
      id: '/marketplace/_layout/listing/$slug/'
      path: '/listing/$slug'
      fullPath: '/marketplace/listing/$slug'
      preLoaderRoute: typeof MarketplaceLayoutListingSlugIndexImport
      parentRoute: typeof MarketplaceLayoutImport
    }
    '/marketplace/_layout/merchant/$id/': {
      id: '/marketplace/_layout/merchant/$id/'
      path: '/merchant/$id'
      fullPath: '/marketplace/merchant/$id'
      preLoaderRoute: typeof MarketplaceLayoutMerchantIdIndexImport
      parentRoute: typeof MarketplaceLayoutImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedDeliveryIndexRoute: typeof AuthenticatedDeliveryIndexRoute
  AuthenticatedDriversIndexRoute: typeof AuthenticatedDriversIndexRoute
  AuthenticatedFleetIndexRoute: typeof AuthenticatedFleetIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWarehouseIndexRoute: typeof AuthenticatedWarehouseIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedDeliveryIndexRoute: AuthenticatedDeliveryIndexRoute,
  AuthenticatedDriversIndexRoute: AuthenticatedDriversIndexRoute,
  AuthenticatedFleetIndexRoute: AuthenticatedFleetIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWarehouseIndexRoute: AuthenticatedWarehouseIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

interface MarketplaceLayoutRouteChildren {
  MarketplaceLayoutMyOrdersRoute: typeof MarketplaceLayoutMyOrdersRoute
  MarketplaceLayoutIndexRoute: typeof MarketplaceLayoutIndexRoute
  MarketplaceLayoutDashboardImportRoute: typeof MarketplaceLayoutDashboardImportRoute
  MarketplaceLayoutDashboardLabelsRoute: typeof MarketplaceLayoutDashboardLabelsRoute
  MarketplaceLayoutOrderIdRoute: typeof MarketplaceLayoutOrderIdRoute
  MarketplaceLayoutOrderTrackRoute: typeof MarketplaceLayoutOrderTrackRoute
  MarketplaceLayoutCartIndexRoute: typeof MarketplaceLayoutCartIndexRoute
  MarketplaceLayoutCheckoutIndexRoute: typeof MarketplaceLayoutCheckoutIndexRoute
  MarketplaceLayoutDashboardIndexRoute: typeof MarketplaceLayoutDashboardIndexRoute
  MarketplaceLayoutListingsIndexRoute: typeof MarketplaceLayoutListingsIndexRoute
  MarketplaceLayoutDashboardOrderIdRoute: typeof MarketplaceLayoutDashboardOrderIdRoute
  MarketplaceLayoutDashboardOrdersAllRoute: typeof MarketplaceLayoutDashboardOrdersAllRoute
  MarketplaceLayoutDashboardBookingsIndexRoute: typeof MarketplaceLayoutDashboardBookingsIndexRoute
  MarketplaceLayoutDashboardListingsIndexRoute: typeof MarketplaceLayoutDashboardListingsIndexRoute
  MarketplaceLayoutDashboardOrdersIndexRoute: typeof MarketplaceLayoutDashboardOrdersIndexRoute
  MarketplaceLayoutDashboardPosIndexRoute: typeof MarketplaceLayoutDashboardPosIndexRoute
  MarketplaceLayoutDashboardSettingsIndexRoute: typeof MarketplaceLayoutDashboardSettingsIndexRoute
  MarketplaceLayoutListingSlugIndexRoute: typeof MarketplaceLayoutListingSlugIndexRoute
  MarketplaceLayoutMerchantIdIndexRoute: typeof MarketplaceLayoutMerchantIdIndexRoute
}

const MarketplaceLayoutRouteChildren: MarketplaceLayoutRouteChildren = {
  MarketplaceLayoutMyOrdersRoute: MarketplaceLayoutMyOrdersRoute,
  MarketplaceLayoutIndexRoute: MarketplaceLayoutIndexRoute,
  MarketplaceLayoutDashboardImportRoute: MarketplaceLayoutDashboardImportRoute,
  MarketplaceLayoutDashboardLabelsRoute: MarketplaceLayoutDashboardLabelsRoute,
  MarketplaceLayoutOrderIdRoute: MarketplaceLayoutOrderIdRoute,
  MarketplaceLayoutOrderTrackRoute: MarketplaceLayoutOrderTrackRoute,
  MarketplaceLayoutCartIndexRoute: MarketplaceLayoutCartIndexRoute,
  MarketplaceLayoutCheckoutIndexRoute: MarketplaceLayoutCheckoutIndexRoute,
  MarketplaceLayoutDashboardIndexRoute: MarketplaceLayoutDashboardIndexRoute,
  MarketplaceLayoutListingsIndexRoute: MarketplaceLayoutListingsIndexRoute,
  MarketplaceLayoutDashboardOrderIdRoute:
    MarketplaceLayoutDashboardOrderIdRoute,
  MarketplaceLayoutDashboardOrdersAllRoute:
    MarketplaceLayoutDashboardOrdersAllRoute,
  MarketplaceLayoutDashboardBookingsIndexRoute:
    MarketplaceLayoutDashboardBookingsIndexRoute,
  MarketplaceLayoutDashboardListingsIndexRoute:
    MarketplaceLayoutDashboardListingsIndexRoute,
  MarketplaceLayoutDashboardOrdersIndexRoute:
    MarketplaceLayoutDashboardOrdersIndexRoute,
  MarketplaceLayoutDashboardPosIndexRoute:
    MarketplaceLayoutDashboardPosIndexRoute,
  MarketplaceLayoutDashboardSettingsIndexRoute:
    MarketplaceLayoutDashboardSettingsIndexRoute,
  MarketplaceLayoutListingSlugIndexRoute:
    MarketplaceLayoutListingSlugIndexRoute,
  MarketplaceLayoutMerchantIdIndexRoute: MarketplaceLayoutMerchantIdIndexRoute,
}

const MarketplaceLayoutRouteWithChildren =
  MarketplaceLayoutRoute._addFileChildren(MarketplaceLayoutRouteChildren)

interface MarketplaceRouteChildren {
  MarketplaceLayoutRoute: typeof MarketplaceLayoutRouteWithChildren
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceLayoutRoute: MarketplaceLayoutRouteWithChildren,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/': typeof ClerkauthRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/blog/manage': typeof BlogManageRoute
  '/blog/new': typeof BlogNewRoute
  '/marketplace': typeof MarketplaceLayoutRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/blog': typeof BlogIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/blog/$slug/edit': typeof BlogSlugEditRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/marketplace/my-orders': typeof MarketplaceLayoutMyOrdersRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/delivery': typeof AuthenticatedDeliveryIndexRoute
  '/drivers': typeof AuthenticatedDriversIndexRoute
  '/fleet': typeof AuthenticatedFleetIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/warehouse': typeof AuthenticatedWarehouseIndexRoute
  '/blog/$slug': typeof BlogSlugIndexRoute
  '/marketplace/': typeof MarketplaceLayoutIndexRoute
  '/marketplace/dashboard/import': typeof MarketplaceLayoutDashboardImportRoute
  '/marketplace/dashboard/labels': typeof MarketplaceLayoutDashboardLabelsRoute
  '/marketplace/order/$id': typeof MarketplaceLayoutOrderIdRoute
  '/marketplace/order/track': typeof MarketplaceLayoutOrderTrackRoute
  '/marketplace/cart': typeof MarketplaceLayoutCartIndexRoute
  '/marketplace/checkout': typeof MarketplaceLayoutCheckoutIndexRoute
  '/marketplace/dashboard': typeof MarketplaceLayoutDashboardIndexRoute
  '/marketplace/listings': typeof MarketplaceLayoutListingsIndexRoute
  '/marketplace/dashboard/order/$id': typeof MarketplaceLayoutDashboardOrderIdRoute
  '/marketplace/dashboard/orders/all': typeof MarketplaceLayoutDashboardOrdersAllRoute
  '/marketplace/dashboard/bookings': typeof MarketplaceLayoutDashboardBookingsIndexRoute
  '/marketplace/dashboard/listings': typeof MarketplaceLayoutDashboardListingsIndexRoute
  '/marketplace/dashboard/orders': typeof MarketplaceLayoutDashboardOrdersIndexRoute
  '/marketplace/dashboard/pos': typeof MarketplaceLayoutDashboardPosIndexRoute
  '/marketplace/dashboard/settings': typeof MarketplaceLayoutDashboardSettingsIndexRoute
  '/marketplace/listing/$slug': typeof MarketplaceLayoutListingSlugIndexRoute
  '/marketplace/merchant/$id': typeof MarketplaceLayoutMerchantIdIndexRoute
}

export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/blog/manage': typeof BlogManageRoute
  '/blog/new': typeof BlogNewRoute
  '/marketplace': typeof MarketplaceLayoutIndexRoute
  '/': typeof AuthenticatedIndexRoute
  '/blog': typeof BlogIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/blog/$slug/edit': typeof BlogSlugEditRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/marketplace/my-orders': typeof MarketplaceLayoutMyOrdersRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/delivery': typeof AuthenticatedDeliveryIndexRoute
  '/drivers': typeof AuthenticatedDriversIndexRoute
  '/fleet': typeof AuthenticatedFleetIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/warehouse': typeof AuthenticatedWarehouseIndexRoute
  '/blog/$slug': typeof BlogSlugIndexRoute
  '/marketplace/dashboard/import': typeof MarketplaceLayoutDashboardImportRoute
  '/marketplace/dashboard/labels': typeof MarketplaceLayoutDashboardLabelsRoute
  '/marketplace/order/$id': typeof MarketplaceLayoutOrderIdRoute
  '/marketplace/order/track': typeof MarketplaceLayoutOrderTrackRoute
  '/marketplace/cart': typeof MarketplaceLayoutCartIndexRoute
  '/marketplace/checkout': typeof MarketplaceLayoutCheckoutIndexRoute
  '/marketplace/dashboard': typeof MarketplaceLayoutDashboardIndexRoute
  '/marketplace/listings': typeof MarketplaceLayoutListingsIndexRoute
  '/marketplace/dashboard/order/$id': typeof MarketplaceLayoutDashboardOrderIdRoute
  '/marketplace/dashboard/orders/all': typeof MarketplaceLayoutDashboardOrdersAllRoute
  '/marketplace/dashboard/bookings': typeof MarketplaceLayoutDashboardBookingsIndexRoute
  '/marketplace/dashboard/listings': typeof MarketplaceLayoutDashboardListingsIndexRoute
  '/marketplace/dashboard/orders': typeof MarketplaceLayoutDashboardOrdersIndexRoute
  '/marketplace/dashboard/pos': typeof MarketplaceLayoutDashboardPosIndexRoute
  '/marketplace/dashboard/settings': typeof MarketplaceLayoutDashboardSettingsIndexRoute
  '/marketplace/listing/$slug': typeof MarketplaceLayoutListingSlugIndexRoute
  '/marketplace/merchant/$id': typeof MarketplaceLayoutMerchantIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/blog/manage': typeof BlogManageRoute
  '/blog/new': typeof BlogNewRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/marketplace/_layout': typeof MarketplaceLayoutRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/blog/$slug/edit': typeof BlogSlugEditRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/marketplace/_layout/my-orders': typeof MarketplaceLayoutMyOrdersRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/delivery/': typeof AuthenticatedDeliveryIndexRoute
  '/_authenticated/drivers/': typeof AuthenticatedDriversIndexRoute
  '/_authenticated/fleet/': typeof AuthenticatedFleetIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/warehouse/': typeof AuthenticatedWarehouseIndexRoute
  '/blog/$slug/': typeof BlogSlugIndexRoute
  '/marketplace/_layout/': typeof MarketplaceLayoutIndexRoute
  '/marketplace/_layout/dashboard/import': typeof MarketplaceLayoutDashboardImportRoute
  '/marketplace/_layout/dashboard/labels': typeof MarketplaceLayoutDashboardLabelsRoute
  '/marketplace/_layout/order/$id': typeof MarketplaceLayoutOrderIdRoute
  '/marketplace/_layout/order/track': typeof MarketplaceLayoutOrderTrackRoute
  '/marketplace/_layout/cart/': typeof MarketplaceLayoutCartIndexRoute
  '/marketplace/_layout/checkout/': typeof MarketplaceLayoutCheckoutIndexRoute
  '/marketplace/_layout/dashboard/': typeof MarketplaceLayoutDashboardIndexRoute
  '/marketplace/_layout/listings/': typeof MarketplaceLayoutListingsIndexRoute
  '/marketplace/_layout/dashboard/order/$id': typeof MarketplaceLayoutDashboardOrderIdRoute
  '/marketplace/_layout/dashboard/orders/all': typeof MarketplaceLayoutDashboardOrdersAllRoute
  '/marketplace/_layout/dashboard/bookings/': typeof MarketplaceLayoutDashboardBookingsIndexRoute
  '/marketplace/_layout/dashboard/listings/': typeof MarketplaceLayoutDashboardListingsIndexRoute
  '/marketplace/_layout/dashboard/orders/': typeof MarketplaceLayoutDashboardOrdersIndexRoute
  '/marketplace/_layout/dashboard/pos/': typeof MarketplaceLayoutDashboardPosIndexRoute
  '/marketplace/_layout/dashboard/settings/': typeof MarketplaceLayoutDashboardSettingsIndexRoute
  '/marketplace/_layout/listing/$slug/': typeof MarketplaceLayoutListingSlugIndexRoute
  '/marketplace/_layout/merchant/$id/': typeof MarketplaceLayoutMerchantIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/clerk'
    | '/settings'
    | '/clerk/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/blog/manage'
    | '/blog/new'
    | '/marketplace'
    | '/'
    | '/blog'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/blog/$slug/edit'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/marketplace/my-orders'
    | '/apps'
    | '/chats'
    | '/delivery'
    | '/drivers'
    | '/fleet'
    | '/help-center'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/warehouse'
    | '/blog/$slug'
    | '/marketplace/'
    | '/marketplace/dashboard/import'
    | '/marketplace/dashboard/labels'
    | '/marketplace/order/$id'
    | '/marketplace/order/track'
    | '/marketplace/cart'
    | '/marketplace/checkout'
    | '/marketplace/dashboard'
    | '/marketplace/listings'
    | '/marketplace/dashboard/order/$id'
    | '/marketplace/dashboard/orders/all'
    | '/marketplace/dashboard/bookings'
    | '/marketplace/dashboard/listings'
    | '/marketplace/dashboard/orders'
    | '/marketplace/dashboard/pos'
    | '/marketplace/dashboard/settings'
    | '/marketplace/listing/$slug'
    | '/marketplace/merchant/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/blog/manage'
    | '/blog/new'
    | '/marketplace'
    | '/'
    | '/blog'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/blog/$slug/edit'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/marketplace/my-orders'
    | '/apps'
    | '/chats'
    | '/delivery'
    | '/drivers'
    | '/fleet'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/warehouse'
    | '/blog/$slug'
    | '/marketplace/dashboard/import'
    | '/marketplace/dashboard/labels'
    | '/marketplace/order/$id'
    | '/marketplace/order/track'
    | '/marketplace/cart'
    | '/marketplace/checkout'
    | '/marketplace/dashboard'
    | '/marketplace/listings'
    | '/marketplace/dashboard/order/$id'
    | '/marketplace/dashboard/orders/all'
    | '/marketplace/dashboard/bookings'
    | '/marketplace/dashboard/listings'
    | '/marketplace/dashboard/orders'
    | '/marketplace/dashboard/pos'
    | '/marketplace/dashboard/settings'
    | '/marketplace/listing/$slug'
    | '/marketplace/merchant/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/blog/manage'
    | '/blog/new'
    | '/marketplace'
    | '/marketplace/_layout'
    | '/_authenticated/'
    | '/blog/'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/blog/$slug/edit'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/marketplace/_layout/my-orders'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/delivery/'
    | '/_authenticated/drivers/'
    | '/_authenticated/fleet/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/warehouse/'
    | '/blog/$slug/'
    | '/marketplace/_layout/'
    | '/marketplace/_layout/dashboard/import'
    | '/marketplace/_layout/dashboard/labels'
    | '/marketplace/_layout/order/$id'
    | '/marketplace/_layout/order/track'
    | '/marketplace/_layout/cart/'
    | '/marketplace/_layout/checkout/'
    | '/marketplace/_layout/dashboard/'
    | '/marketplace/_layout/listings/'
    | '/marketplace/_layout/dashboard/order/$id'
    | '/marketplace/_layout/dashboard/orders/all'
    | '/marketplace/_layout/dashboard/bookings/'
    | '/marketplace/_layout/dashboard/listings/'
    | '/marketplace/_layout/dashboard/orders/'
    | '/marketplace/_layout/dashboard/pos/'
    | '/marketplace/_layout/dashboard/settings/'
    | '/marketplace/_layout/listing/$slug/'
    | '/marketplace/_layout/merchant/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  BlogManageRoute: typeof BlogManageRoute
  BlogNewRoute: typeof BlogNewRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  BlogIndexRoute: typeof BlogIndexRoute
  BlogSlugEditRoute: typeof BlogSlugEditRoute
  BlogSlugIndexRoute: typeof BlogSlugIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  BlogManageRoute: BlogManageRoute,
  BlogNewRoute: BlogNewRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  BlogIndexRoute: BlogIndexRoute,
  BlogSlugEditRoute: BlogSlugEditRoute,
  BlogSlugIndexRoute: BlogSlugIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/clerk",
        "/(auth)/forgot-password",
        "/(auth)/otp",
        "/(auth)/sign-in",
        "/(auth)/sign-in-2",
        "/(auth)/sign-up",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503",
        "/blog/manage",
        "/blog/new",
        "/marketplace",
        "/blog/",
        "/blog/$slug/edit",
        "/blog/$slug/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/settings",
        "/_authenticated/",
        "/_authenticated/apps/",
        "/_authenticated/chats/",
        "/_authenticated/delivery/",
        "/_authenticated/drivers/",
        "/_authenticated/fleet/",
        "/_authenticated/help-center/",
        "/_authenticated/tasks/",
        "/_authenticated/users/",
        "/_authenticated/warehouse/"
      ]
    },
    "/clerk": {
      "filePath": "clerk/route.tsx",
      "children": [
        "/clerk/(auth)",
        "/clerk/_authenticated"
      ]
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/account",
        "/_authenticated/settings/appearance",
        "/_authenticated/settings/display",
        "/_authenticated/settings/notifications",
        "/_authenticated/settings/"
      ]
    },
    "/clerk/(auth)": {
      "filePath": "clerk/(auth)/route.tsx",
      "parent": "/clerk",
      "children": [
        "/clerk/(auth)/sign-in",
        "/clerk/(auth)/sign-up"
      ]
    },
    "/clerk/_authenticated": {
      "filePath": "clerk/_authenticated/route.tsx",
      "parent": "/clerk",
      "children": [
        "/clerk/_authenticated/user-management"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.tsx"
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/(auth)/sign-in-2": {
      "filePath": "(auth)/sign-in-2.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.tsx"
    },
    "/blog/manage": {
      "filePath": "blog/manage.tsx"
    },
    "/blog/new": {
      "filePath": "blog/new.tsx"
    },
    "/marketplace": {
      "filePath": "marketplace",
      "children": [
        "/marketplace/_layout"
      ]
    },
    "/marketplace/_layout": {
      "filePath": "marketplace/_layout.tsx",
      "parent": "/marketplace",
      "children": [
        "/marketplace/_layout/my-orders",
        "/marketplace/_layout/",
        "/marketplace/_layout/dashboard/import",
        "/marketplace/_layout/dashboard/labels",
        "/marketplace/_layout/order/$id",
        "/marketplace/_layout/order/track",
        "/marketplace/_layout/cart/",
        "/marketplace/_layout/checkout/",
        "/marketplace/_layout/dashboard/",
        "/marketplace/_layout/listings/",
        "/marketplace/_layout/dashboard/order/$id",
        "/marketplace/_layout/dashboard/orders/all",
        "/marketplace/_layout/dashboard/bookings/",
        "/marketplace/_layout/dashboard/listings/",
        "/marketplace/_layout/dashboard/orders/",
        "/marketplace/_layout/dashboard/pos/",
        "/marketplace/_layout/dashboard/settings/",
        "/marketplace/_layout/listing/$slug/",
        "/marketplace/_layout/merchant/$id/"
      ]
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/blog/": {
      "filePath": "blog/index.tsx"
    },
    "/_authenticated/settings/account": {
      "filePath": "_authenticated/settings/account.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/appearance": {
      "filePath": "_authenticated/settings/appearance.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/display": {
      "filePath": "_authenticated/settings/display.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/notifications": {
      "filePath": "_authenticated/settings/notifications.tsx",
      "parent": "/_authenticated/settings"
    },
    "/blog/$slug/edit": {
      "filePath": "blog/$slug/edit.tsx"
    },
    "/clerk/(auth)/sign-in": {
      "filePath": "clerk/(auth)/sign-in.tsx",
      "parent": "/clerk/(auth)"
    },
    "/clerk/(auth)/sign-up": {
      "filePath": "clerk/(auth)/sign-up.tsx",
      "parent": "/clerk/(auth)"
    },
    "/clerk/_authenticated/user-management": {
      "filePath": "clerk/_authenticated/user-management.tsx",
      "parent": "/clerk/_authenticated"
    },
    "/marketplace/_layout/my-orders": {
      "filePath": "marketplace/_layout/my-orders.tsx",
      "parent": "/marketplace/_layout"
    },
    "/_authenticated/apps/": {
      "filePath": "_authenticated/apps/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/chats/": {
      "filePath": "_authenticated/chats/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/delivery/": {
      "filePath": "_authenticated/delivery/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/drivers/": {
      "filePath": "_authenticated/drivers/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/fleet/": {
      "filePath": "_authenticated/fleet/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/help-center/": {
      "filePath": "_authenticated/help-center/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/tasks/": {
      "filePath": "_authenticated/tasks/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/users/": {
      "filePath": "_authenticated/users/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/warehouse/": {
      "filePath": "_authenticated/warehouse/index.tsx",
      "parent": "/_authenticated"
    },
    "/blog/$slug/": {
      "filePath": "blog/$slug/index.tsx"
    },
    "/marketplace/_layout/": {
      "filePath": "marketplace/_layout/index.tsx",
      "parent": "/marketplace/_layout"
    },
    "/marketplace/_layout/dashboard/import": {
      "filePath": "marketplace/_layout/dashboard/import.tsx",
      "parent": "/marketplace/_layout"
    },
    "/marketplace/_layout/dashboard/labels": {
      "filePath": "marketplace/_layout/dashboard/labels.tsx",
      "parent": "/marketplace/_layout"
    },
    "/marketplace/_layout/order/$id": {
      "filePath": "marketplace/_layout/order/$id.tsx",
      "parent": "/marketplace/_layout"
    },
    "/marketplace/_layout/order/track": {
      "filePath": "marketplace/_layout/order/track.tsx",
      "parent": "/marketplace/_layout"
    },
    "/marketplace/_layout/cart/": {
      "filePath": "marketplace/_layout/cart/index.tsx",
      "parent": "/marketplace/_layout"
    },
    "/marketplace/_layout/checkout/": {
      "filePath": "marketplace/_layout/checkout/index.tsx",
      "parent": "/marketplace/_layout"
    },
    "/marketplace/_layout/dashboard/": {
      "filePath": "marketplace/_layout/dashboard/index.tsx",
      "parent": "/marketplace/_layout"
    },
    "/marketplace/_layout/listings/": {
      "filePath": "marketplace/_layout/listings/index.tsx",
      "parent": "/marketplace/_layout"
    },
    "/marketplace/_layout/dashboard/order/$id": {
      "filePath": "marketplace/_layout/dashboard/order/$id.tsx",
      "parent": "/marketplace/_layout"
    },
    "/marketplace/_layout/dashboard/orders/all": {
      "filePath": "marketplace/_layout/dashboard/orders/all.tsx",
      "parent": "/marketplace/_layout"
    },
    "/marketplace/_layout/dashboard/bookings/": {
      "filePath": "marketplace/_layout/dashboard/bookings/index.tsx",
      "parent": "/marketplace/_layout"
    },
    "/marketplace/_layout/dashboard/listings/": {
      "filePath": "marketplace/_layout/dashboard/listings/index.tsx",
      "parent": "/marketplace/_layout"
    },
    "/marketplace/_layout/dashboard/orders/": {
      "filePath": "marketplace/_layout/dashboard/orders/index.tsx",
      "parent": "/marketplace/_layout"
    },
    "/marketplace/_layout/dashboard/pos/": {
      "filePath": "marketplace/_layout/dashboard/pos/index.tsx",
      "parent": "/marketplace/_layout"
    },
    "/marketplace/_layout/dashboard/settings/": {
      "filePath": "marketplace/_layout/dashboard/settings/index.tsx",
      "parent": "/marketplace/_layout"
    },
    "/marketplace/_layout/listing/$slug/": {
      "filePath": "marketplace/_layout/listing/$slug/index.tsx",
      "parent": "/marketplace/_layout"
    },
    "/marketplace/_layout/merchant/$id/": {
      "filePath": "marketplace/_layout/merchant/$id/index.tsx",
      "parent": "/marketplace/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
